
import __ASTRO_IMAGE_IMPORT_QmBnq from "./assign2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fassignment2%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1VpDIm from "./assign3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fassignment3%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZdFpWv from "./assign1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fassignment1%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1dHpF5 from "./cpu-gpu.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fcompute-sandbox%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1Ae190 from "./assign3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fassignment4%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z8zi67 from "./gputsl.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fwebgpu-shaders%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_2hsaje from "./turnstile.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fturnstile%2Findex.md";
export default new Map([["./assign2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fassignment2%2Findex.mdx", __ASTRO_IMAGE_IMPORT_QmBnq], ["./assign3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fassignment3%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1VpDIm], ["./assign1.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fassignment1%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZdFpWv], ["./cpu-gpu.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fcompute-sandbox%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1dHpF5], ["./assign3.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fassignment4%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1Ae190], ["./gputsl.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fwebgpu-shaders%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z8zi67], ["./turnstile.png?astroContentImageFlag=&importer=src%2Fcontent%2Fpost%2Fturnstile%2Findex.md", __ASTRO_IMAGE_IMPORT_2hsaje]]);
		